# stack.yaml
resolver: lts-20.0

# VULNERABILITY: Mixing real external repo with official Hackage
package-indices:
- download-prefix: https://hackage.fpcomplete.com/  # Real external repo
- download-prefix: https://hackage.haskell.org/     # Official repo

extra-deps:
- company-auth-1.0.0      # Realistic internal package name
- internal-utils-2.1.0    # Another realistic internal name
